### ISSUE TITLE
你好，我用vs2013，生成commlibrary的时候出问题

### ISSUE THREAD

**Issue by benjious** [dathlin/ClientServerProject#1]
![default](https://user-images.githubusercontent.com/17263458/30780603-70521a7a-a141-11e7-9d48-c39e838cf02f.PNG)

**Comment by dathlin** [comment]
肯定是有问题的，我使用的是visual studio2017开发的代码，使用的是C#7.0语法，而vs2013版只支持C#5.0语法，vs2015版只支持C#6.0语法，因为新的语法识别不了，所以报错。
