### ISSUE TITLE
运行例子报了几个错

### ISSUE THREAD

**Issue by sindey1982** [dathlin/ClientServerProject#6]

**Comment by sindey1982** [comment]
UserClient.LogNet = new LogNetDateTime(Application.StartupPath + @"\Logs", GenerateMode.ByEveryDay);
System.TypeInitializationException:““ClientsLibrary.UserClient”的类型初始值设定项引发异常。”
MissingMethodException: 找不到方法:“System.String HslCommunication.BasicFramework.SoftAuthorize.GetInfo()”。


UserClient.JsonSettings.FileSavePath = Application.StartupPath + @"\JsonSettings.txt";
System.TypeInitializationException:““ClientsLibrary.UserClient”的类型初始值设定项引发异常。”
MissingMethodException: 找不到方法:“System.String HslCommunication.BasicFramework.SoftAuthorize.GetInfo()”。

**Comment by sindey1982** [comment]
使用了最新的7.0版本导致的 改成5开头的版本就可以了

**Comment by dathlin** [comment]
好的，我看看，修改一下
